apiVersion: v1
kind: Service
metadata:
  name: abc
  namespace: namespace-workflow-1750045370759
  labels:
    app.kubernetes.io/name: abc
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: abc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080